### ISSUE TITLE
export size

### ISSUE THREAD

**Issue by lesath3d** [playcanvas/supersplat#302] opened 2024-11-27 10:08 UTC
hello, I can't save as files which are bigger than 1,5GB and 6,5mill splats. if the limitation would be at least 10mill splats and 2-2,5GB for the detailed/big scans, that would be great.

**Comment by slimbuck** [comment] 2024-11-27 10:12
Hi @lesath3d ,

My macbook can export much larger scenes than that!

Few questions:
1) what happens when you attempt to save?
2) which platform and browser is this?
3) which export format is this?

Thanks!

**Comment by lesath3d** [comment] 2024-11-27 10:35
1.: Error Loading File: Array buffer allocation failed while saving file
2.: Chrome
3.: Im using the "Save as", but it happens every single type of export

**Comment by slimbuck** [comment] 2024-11-27 10:38
Thanks, which platform? (Machine and OS)

**Comment by lesath3d** [comment] 2024-11-27 11:11
win 11 pro, 64gb ram, rtx  3090, ryzen 9 5900X

**Comment by simonbethke** [comment] 2024-11-27 14:39
Is that a file that you can provide for testing?
Is that something that happened once or can you somehow load but not save the file?
I once ran into the issue, that my undo-memory blew the app. I was able to save my work by clearing that manually in the guts of the memory :)
Thats the reason for implementing the Selection-Compression PR that aparently nobody is interested in https://github.com/playcanvas/supersplat/pull/207

**Comment by lesath3d** [comment] 2024-11-27 16:01
I loaded & cleaned some splats and I cant save out with "save as". I deleted the half and saved out, hit undo, invert, delete that part as well, saved out. I think it shouldn't the memory issue.

**Comment by simonbethke** [comment] 2024-11-27 17:37
Well, with every selection you make you increase the memory usage. I would suggest some kind of emergency-save function, that can be used in case the normal save fails. The emergency save would then warn the user and allow purging all memory that is not required for saving. Still, I assume that at some point the browser will need at least two times the size of the loaded data as memory. And chrome at least on Windows might have a hard limit there.

**Comment by willeastcott** [comment] 2024-11-28 11:07
@lesath3d Have you tried installing SuperSplat as a PWA?

https://blog.playcanvas.com/a-faster-supersplat-with-pwa-support/#pwa-support

I'm wondering whether Chrome will grant SuperSplat more memory in that mode.

**Comment by lesath3d** [comment] 2024-11-28 12:15
just tried, but still firefox looks the best. that can save until 2GB. 
I tried on another PC with ryzen 9 5900X, 128gb ram and rtx 6000 ada, but same result

**Comment by simonbethke** [comment] 2024-11-28 16:18
hm, I cannot confirm this behavior. I just stored a 3.6GB file with chrome on windows.

**Comment by slimbuck** [comment] 2024-12-12 14:21
Hi @lesath3d

Did you find any solution here? I don't _think_ the issue is on our side, but more likely your platform or browser settings. Since we can't control the browser memory limits and can't replicate the issue, I'm going to close this ticket.

If you manage to figure out what the issue is/was, please let us know.

And feel free to reopen the issue if you think there is something we can do to help.

**Closed by slimbuck** 2024-12-12 14:21 UTC

**Comment by lesath3d** [comment] 2024-12-12 16:08
hello @slimbuck ,
sadly no. The limits on firefox is 2 gb at this moment. This looks the best option now, When I need to do anything with bigger splats I'm going to split it to parts and merge them with another software. I'd love to reopen this ticket, but if you can't do anything it looks pointless now.

**Comment by simonbethke** [comment] 2024-12-12 16:14
This sounds almost as if you were using a 32bit version of the browser

**Comment by lesath3d** [comment] 2024-12-13 13:52
it's 64bit version of the 1333.0 firefox
