### ISSUE TITLE
[Feature Request] Ability to modify the size of parts of GS

### ISSUE THREAD

**Issue by equilento** [playcanvas/supersplat#160] opened 2024-08-09 11:14 UTC
It would be an AWESOME feature if we could modify part of splats. For instance enlarge/reduce, stretch/squeeze etc. parts of 3DGS.

**Comment by OrangeSodahub** [comment] 2024-08-19 10:12
@equilento Hi, I have the same question, did you figure that out?

**Comment by slimbuck** [comment] 2024-08-19 10:26
Duplicate of #148.

**Closed by slimbuck** 2024-08-19 10:26 UTC
